spring:
   application:
      name: template-service
   datasource:
      driverClassName: org.h2.Driver
app:
   security:
      partners:
         internal: randomkey
      secureRoutes:
       - /api
       - /rpc
---

spring:
   profiles: test

---

spring:
   profiles: production
   datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.59.106:5432/postgres
      username: postgres
      password: pass
      ddl-auto: create-drop
   jpa:
      database: postgres
      show-sql: true