spring:
   application:
      name: template-service
   datasource:
      driverClassName: org.h2.Driver
service:
   partners:
      webs: CNZNeEuTWeLrnImRTUDtJIkw7PFERuuO7GXoJbgnclpI7Is77IFvcurxl4LJ
      vp: G4SKNPYmv9j4WSyhrqyAmRTUDY85x2nGourhqUtJIkw7PFErxl4LJg1yr7Go
      internal: U9WuAWc1y50UNQHAxriNplgDdNRjOXerT73KdemBA1EJ3jrOupXUo8m9zvIV
   secureRoutes:
    - /api
    - /rpc
---

spring:
   profiles: test

---

spring:
   profiles: production
   datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.59.106:5432/postgres
      username: postgres
      password: pass
      ddl-auto: create-drop
   jpa:
      database: postgres
      show-sql: true